// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmsBackend.Data;

#nullable disable

namespace SmsBackend.Data.Migrations
{
    [DbContext(typeof(SmsDbContext))]
    [Migration("20260830191200_InitialTiposMovimiento")]
    partial class InitialTiposMovimiento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmsBackend.Domain.TiposMovimiento.TipoMovimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("FormatoBoletaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HabilitaCalidad")
                        .HasColumnType("bit");

                    b.Property<bool>("HabilitaCompostera")
                        .HasColumnType("bit");

                    b.Property<bool>("HabilitaDatosFinca")
                        .HasColumnType("bit");

                    b.Property<bool>("HabilitaDetalleFruta")
                        .HasColumnType("bit");

                    b.Property<bool>("HabilitaMarchamos")
                        .HasColumnType("bit");

                    b.Property<bool>("HabilitaQR")
                        .HasColumnType("bit");

                    b.Property<bool>("IntegracionD365")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("TipoMovimiento", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
