// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmsBackend.Data;

#nullable disable

namespace SmsBackend.Data.Migrations
{
    [DbContext(typeof(SmsDbContext))]
    [Migration("20260902050132_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmsBackend.Domain.Basculas.Bascula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<bool>("Aprovisionada")
                        .HasColumnType("bit");

                    b.Property<int?>("BitsDatos")
                        .HasColumnType("int");

                    b.Property<Guid>("CentroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CodigoAprovisionamiento")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime?>("CodigoAprovisionamientoExpira")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("ModoComunicacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Puerto")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PuertoTcp")
                        .HasColumnType("int");

                    b.Property<string>("TipoConexion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Velocidad")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CentroId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Bascula", (string)null);
                });

            modelBuilder.Entity("SmsBackend.Domain.Boletas.Boleta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BasculaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BasculaSalidaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BoletaOrigenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BoletaReemplazoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CreadaOffline")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EstadoSync")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaHoraAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaHoraSalida")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NumeroBoleta")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("OrigenPesoIngreso")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OrigenPesoSalida")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("PesoIngreso")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("PesoNeto")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("PesoSalida")
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid?>("PreIngresoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RespuestaD365Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TipoMovimientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsuarioAnula")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UsuarioAutoriza")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UsuarioSalida")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("BasculaId");

                    b.HasIndex("BasculaSalidaId");

                    b.HasIndex("BoletaOrigenId");

                    b.HasIndex("BoletaReemplazoId");

                    b.HasIndex("NumeroBoleta")
                        .IsUnique();

                    b.HasIndex("TipoMovimientoId");

                    b.ToTable("Boleta", (string)null);
                });

            modelBuilder.Entity("SmsBackend.Domain.Boletas.Valores.BoletaValorCampo", b =>
                {
                    b.Property<Guid>("BoletaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ocurrencia")
                        .HasColumnType("int");

                    b.Property<Guid>("SeccionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("ValorBooleano")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ValorFecha")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ValorMaestroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("ValorNumero")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ValorTexto")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("BoletaId", "CampoId", "Ocurrencia");

                    b.HasIndex("SeccionId");

                    b.HasIndex("ValorMaestroId");

                    b.HasIndex("BoletaId", "SeccionId");

                    b.HasIndex("CampoId", "ValorNumero");

                    b.ToTable("BoletaValorCampo", null, t =>
                        {
                            t.HasCheckConstraint("CK_BoletaValorCampo_UnSoloValor", "(CASE WHEN ValorTexto IS NULL THEN 0 ELSE 1 END + CASE WHEN ValorNumero IS NULL THEN 0 ELSE 1 END + CASE WHEN ValorFecha IS NULL THEN 0 ELSE 1 END + CASE WHEN ValorBooleano IS NULL THEN 0 ELSE 1 END + CASE WHEN ValorMaestroId IS NULL THEN 0 ELSE 1 END) = 1");
                        });
                });

            modelBuilder.Entity("SmsBackend.Domain.Configuracion.Campo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Configuracion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etiqueta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<bool>("Requerido")
                        .HasColumnType("bit");

                    b.Property<Guid>("SeccionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoCampo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoCatalogoRef")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("VigenteDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VigenteHasta")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SeccionId", "Clave")
                        .IsUnique()
                        .HasFilter("[VigenteHasta] IS NULL");

                    b.HasIndex("SeccionId", "Orden");

                    b.ToTable("Campo", (string)null);
                });

            modelBuilder.Entity("SmsBackend.Domain.Configuracion.Seccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Cardinalidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Estandar")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<bool>("Reportable")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.ToTable("Seccion", (string)null);
                });

            modelBuilder.Entity("SmsBackend.Domain.Configuracion.TipoMovimientoSeccion", b =>
                {
                    b.Property<Guid>("TipoMovimientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SeccionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("VigenteDesde")
                        .HasColumnType("datetime2");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<bool>("Requerida")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("VigenteHasta")
                        .HasColumnType("datetime2");

                    b.HasKey("TipoMovimientoId", "SeccionId", "VigenteDesde");

                    b.HasIndex("SeccionId");

                    b.HasIndex("TipoMovimientoId", "SeccionId")
                        .IsUnique()
                        .HasFilter("[VigenteHasta] IS NULL");

                    b.ToTable("TipoMovimientoSeccion", (string)null);
                });

            modelBuilder.Entity("SmsBackend.Domain.Maestros.Maestro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DatosAdicionales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FusionadoConId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TipoCatalogo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("FusionadoConId");

                    b.HasIndex("TipoCatalogo", "Codigo")
                        .IsUnique();

                    b.ToTable("Maestro", (string)null);
                });

            modelBuilder.Entity("SmsBackend.Domain.TiposMovimiento.TipoMovimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("FormatoBoletaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("GeneraQR")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OperacionD365")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("TipoMovimiento", (string)null);
                });

            modelBuilder.Entity("SmsBackend.Domain.Basculas.Bascula", b =>
                {
                    b.HasOne("SmsBackend.Domain.Maestros.Maestro", null)
                        .WithMany()
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmsBackend.Domain.Boletas.Boleta", b =>
                {
                    b.HasOne("SmsBackend.Domain.Basculas.Bascula", null)
                        .WithMany()
                        .HasForeignKey("BasculaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmsBackend.Domain.Basculas.Bascula", null)
                        .WithMany()
                        .HasForeignKey("BasculaSalidaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmsBackend.Domain.Boletas.Boleta", null)
                        .WithMany()
                        .HasForeignKey("BoletaOrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmsBackend.Domain.Boletas.Boleta", null)
                        .WithMany()
                        .HasForeignKey("BoletaReemplazoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmsBackend.Domain.TiposMovimiento.TipoMovimiento", null)
                        .WithMany()
                        .HasForeignKey("TipoMovimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmsBackend.Domain.Boletas.Valores.BoletaValorCampo", b =>
                {
                    b.HasOne("SmsBackend.Domain.Boletas.Boleta", null)
                        .WithMany()
                        .HasForeignKey("BoletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmsBackend.Domain.Configuracion.Campo", null)
                        .WithMany()
                        .HasForeignKey("CampoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmsBackend.Domain.Configuracion.Seccion", null)
                        .WithMany()
                        .HasForeignKey("SeccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmsBackend.Domain.Maestros.Maestro", null)
                        .WithMany()
                        .HasForeignKey("ValorMaestroId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SmsBackend.Domain.Configuracion.Campo", b =>
                {
                    b.HasOne("SmsBackend.Domain.Configuracion.Seccion", null)
                        .WithMany()
                        .HasForeignKey("SeccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmsBackend.Domain.Configuracion.TipoMovimientoSeccion", b =>
                {
                    b.HasOne("SmsBackend.Domain.Configuracion.Seccion", null)
                        .WithMany()
                        .HasForeignKey("SeccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmsBackend.Domain.TiposMovimiento.TipoMovimiento", null)
                        .WithMany()
                        .HasForeignKey("TipoMovimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmsBackend.Domain.Maestros.Maestro", b =>
                {
                    b.HasOne("SmsBackend.Domain.Maestros.Maestro", null)
                        .WithMany()
                        .HasForeignKey("FusionadoConId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
