// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmsBackend.Data;

#nullable disable

namespace SmsBackend.Data.Migrations
{
    [DbContext(typeof(SmsDbContext))]
    [Migration("20260830222223_AddBascula")]
    partial class AddBascula
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmsBackend.Domain.Basculas.Bascula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<bool>("Aprovisionada")
                        .HasColumnType("bit");

                    b.Property<int?>("BitsDatos")
                        .HasColumnType("int");

                    b.Property<Guid>("CentroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CodigoAprovisionamiento")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime?>("CodigoAprovisionamientoExpira")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("ModoComunicacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Puerto")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PuertoTcp")
                        .HasColumnType("int");

                    b.Property<string>("TipoConexion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Velocidad")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CentroId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Bascula", (string)null);
                });

            modelBuilder.Entity("SmsBackend.Domain.Maestros.Maestro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DatosAdicionales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FusionadoConId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TipoCatalogo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("FusionadoConId");

                    b.HasIndex("TipoCatalogo", "Codigo")
                        .IsUnique();

                    b.ToTable("Maestro", (string)null);
                });

            modelBuilder.Entity("SmsBackend.Domain.TiposMovimiento.TipoMovimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("FormatoBoletaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HabilitaCalidad")
                        .HasColumnType("bit");

                    b.Property<bool>("HabilitaCompostera")
                        .HasColumnType("bit");

                    b.Property<bool>("HabilitaDatosFinca")
                        .HasColumnType("bit");

                    b.Property<bool>("HabilitaDetalleFruta")
                        .HasColumnType("bit");

                    b.Property<bool>("HabilitaMarchamos")
                        .HasColumnType("bit");

                    b.Property<bool>("HabilitaQR")
                        .HasColumnType("bit");

                    b.Property<bool>("IntegracionD365")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("TipoMovimiento", (string)null);
                });

            modelBuilder.Entity("SmsBackend.Domain.Basculas.Bascula", b =>
                {
                    b.HasOne("SmsBackend.Domain.Maestros.Maestro", null)
                        .WithMany()
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmsBackend.Domain.Maestros.Maestro", b =>
                {
                    b.HasOne("SmsBackend.Domain.Maestros.Maestro", null)
                        .WithMany()
                        .HasForeignKey("FusionadoConId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
