// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmsBackend.Data;

#nullable disable

namespace SmsBackend.Data.Migrations
{
    [DbContext(typeof(SmsDbContext))]
    partial class SmsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmsBackend.Domain.Basculas.Bascula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<bool>("Aprovisionada")
                        .HasColumnType("bit");

                    b.Property<int?>("BitsDatos")
                        .HasColumnType("int");

                    b.Property<Guid>("CentroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CodigoAprovisionamiento")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime?>("CodigoAprovisionamientoExpira")
                        .HasColumnType("datetime2");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("ModoComunicacion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Puerto")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("PuertoTcp")
                        .HasColumnType("int");

                    b.Property<string>("TipoConexion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Velocidad")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CentroId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Bascula", (string)null);
                });

            modelBuilder.Entity("SmsBackend.Domain.Boletas.Boleta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlmacenDestinoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AlmacenOrigenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BasculaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BasculaSalidaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BoletaOrigenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BoletaReemplazoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CreadaOffline")
                        .HasColumnType("bit");

                    b.Property<Guid>("EquipoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EstadoSync")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaHoraIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaHoraSalida")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NumeroBoleta")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("OrigenPesoIngreso")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("OrigenPesoSalida")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("PesoIngreso")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("PesoNeto")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("PesoSalida")
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid>("PilotoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RespuestaD365Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("TerceroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TipoMovimientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TransportistaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsuarioAnula")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UsuarioAutoriza")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UsuarioIngreso")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UsuarioSalida")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("AlmacenDestinoId");

                    b.HasIndex("AlmacenOrigenId");

                    b.HasIndex("BasculaId");

                    b.HasIndex("BasculaSalidaId");

                    b.HasIndex("BoletaOrigenId");

                    b.HasIndex("BoletaReemplazoId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("NumeroBoleta")
                        .IsUnique();

                    b.HasIndex("PilotoId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("TerceroId");

                    b.HasIndex("TipoMovimientoId");

                    b.HasIndex("TransportistaId");

                    b.ToTable("Boleta", (string)null);
                });

            modelBuilder.Entity("SmsBackend.Domain.Boletas.Extensiones.BoletaCalidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Acidez")
                        .HasColumnType("decimal(8,2)");

                    b.Property<Guid>("BoletaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("DOBI")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("Humedad")
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("Luz")
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("NumeroRevisionQA")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Temperatura")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("BoletaId")
                        .IsUnique();

                    b.ToTable("BoletaCalidad", (string)null);
                });

            modelBuilder.Entity("SmsBackend.Domain.Boletas.Extensiones.BoletaCaracteristica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoletaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("CaracteristicaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BoletaId");

                    b.HasIndex("CaracteristicaId");

                    b.ToTable("BoletaCaracteristica", (string)null);
                });

            modelBuilder.Entity("SmsBackend.Domain.Boletas.Extensiones.BoletaCompostera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoletaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CUI")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("CamaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CicloId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SeccionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BoletaId")
                        .IsUnique();

                    b.HasIndex("CamaId");

                    b.HasIndex("CicloId");

                    b.HasIndex("SeccionId");

                    b.ToTable("BoletaCompostera", (string)null);
                });

            modelBuilder.Entity("SmsBackend.Domain.Boletas.Extensiones.BoletaDetalleFruta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoletaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PedunculoLargo")
                        .HasColumnType("int");

                    b.Property<int>("RacimosMaduros")
                        .HasColumnType("int");

                    b.Property<int>("RacimosPasados")
                        .HasColumnType("int");

                    b.Property<int>("RacimosSobreMaduros")
                        .HasColumnType("int");

                    b.Property<int>("RacimosVerdes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BoletaId")
                        .IsUnique();

                    b.ToTable("BoletaDetalleFruta", (string)null);
                });

            modelBuilder.Entity("SmsBackend.Domain.Configuracion.Campo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Configuracion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Etiqueta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<bool>("Requerido")
                        .HasColumnType("bit");

                    b.Property<Guid>("SeccionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoCampo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoCatalogoRef")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("VigenteDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VigenteHasta")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SeccionId", "Clave")
                        .IsUnique()
                        .HasFilter("[VigenteHasta] IS NULL");

                    b.HasIndex("SeccionId", "Orden");

                    b.ToTable("Campo", (string)null);
                });

            modelBuilder.Entity("SmsBackend.Domain.Configuracion.Seccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Cardinalidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Estandar")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<bool>("Reportable")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique();

                    b.ToTable("Seccion", (string)null);
                });

            modelBuilder.Entity("SmsBackend.Domain.Configuracion.TipoMovimientoSeccion", b =>
                {
                    b.Property<Guid>("TipoMovimientoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SeccionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("VigenteDesde")
                        .HasColumnType("datetime2");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<bool>("Requerida")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("VigenteHasta")
                        .HasColumnType("datetime2");

                    b.HasKey("TipoMovimientoId", "SeccionId", "VigenteDesde");

                    b.HasIndex("SeccionId");

                    b.HasIndex("TipoMovimientoId", "SeccionId")
                        .IsUnique()
                        .HasFilter("[VigenteHasta] IS NULL");

                    b.ToTable("TipoMovimientoSeccion", (string)null);
                });

            modelBuilder.Entity("SmsBackend.Domain.Maestros.Maestro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DatosAdicionales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FusionadoConId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TipoCatalogo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("FusionadoConId");

                    b.HasIndex("TipoCatalogo", "Codigo")
                        .IsUnique();

                    b.ToTable("Maestro", (string)null);
                });

            modelBuilder.Entity("SmsBackend.Domain.TiposMovimiento.TipoMovimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("FormatoBoletaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("HabilitaCalidad")
                        .HasColumnType("bit");

                    b.Property<bool>("HabilitaCompostera")
                        .HasColumnType("bit");

                    b.Property<bool>("HabilitaDatosFinca")
                        .HasColumnType("bit");

                    b.Property<bool>("HabilitaDetalleFruta")
                        .HasColumnType("bit");

                    b.Property<bool>("HabilitaMarchamos")
                        .HasColumnType("bit");

                    b.Property<bool>("HabilitaQR")
                        .HasColumnType("bit");

                    b.Property<bool>("IntegracionD365")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prefijo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("TipoMovimiento", (string)null);
                });

            modelBuilder.Entity("SmsBackend.Domain.Basculas.Bascula", b =>
                {
                    b.HasOne("SmsBackend.Domain.Maestros.Maestro", null)
                        .WithMany()
                        .HasForeignKey("CentroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmsBackend.Domain.Boletas.Boleta", b =>
                {
                    b.HasOne("SmsBackend.Domain.Maestros.Maestro", null)
                        .WithMany()
                        .HasForeignKey("AlmacenDestinoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmsBackend.Domain.Maestros.Maestro", null)
                        .WithMany()
                        .HasForeignKey("AlmacenOrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmsBackend.Domain.Basculas.Bascula", null)
                        .WithMany()
                        .HasForeignKey("BasculaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmsBackend.Domain.Basculas.Bascula", null)
                        .WithMany()
                        .HasForeignKey("BasculaSalidaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmsBackend.Domain.Boletas.Boleta", null)
                        .WithMany()
                        .HasForeignKey("BoletaOrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmsBackend.Domain.Boletas.Boleta", null)
                        .WithMany()
                        .HasForeignKey("BoletaReemplazoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmsBackend.Domain.Maestros.Maestro", null)
                        .WithMany()
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmsBackend.Domain.Maestros.Maestro", null)
                        .WithMany()
                        .HasForeignKey("PilotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmsBackend.Domain.Maestros.Maestro", null)
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmsBackend.Domain.Maestros.Maestro", null)
                        .WithMany()
                        .HasForeignKey("TerceroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmsBackend.Domain.TiposMovimiento.TipoMovimiento", null)
                        .WithMany()
                        .HasForeignKey("TipoMovimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmsBackend.Domain.Maestros.Maestro", null)
                        .WithMany()
                        .HasForeignKey("TransportistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmsBackend.Domain.Boletas.Extensiones.BoletaCalidad", b =>
                {
                    b.HasOne("SmsBackend.Domain.Boletas.Boleta", null)
                        .WithMany()
                        .HasForeignKey("BoletaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmsBackend.Domain.Boletas.Extensiones.BoletaCaracteristica", b =>
                {
                    b.HasOne("SmsBackend.Domain.Boletas.Boleta", null)
                        .WithMany()
                        .HasForeignKey("BoletaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmsBackend.Domain.Maestros.Maestro", null)
                        .WithMany()
                        .HasForeignKey("CaracteristicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmsBackend.Domain.Boletas.Extensiones.BoletaCompostera", b =>
                {
                    b.HasOne("SmsBackend.Domain.Boletas.Boleta", null)
                        .WithMany()
                        .HasForeignKey("BoletaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmsBackend.Domain.Maestros.Maestro", null)
                        .WithMany()
                        .HasForeignKey("CamaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmsBackend.Domain.Maestros.Maestro", null)
                        .WithMany()
                        .HasForeignKey("CicloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmsBackend.Domain.Maestros.Maestro", null)
                        .WithMany()
                        .HasForeignKey("SeccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmsBackend.Domain.Boletas.Extensiones.BoletaDetalleFruta", b =>
                {
                    b.HasOne("SmsBackend.Domain.Boletas.Boleta", null)
                        .WithMany()
                        .HasForeignKey("BoletaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmsBackend.Domain.Configuracion.Campo", b =>
                {
                    b.HasOne("SmsBackend.Domain.Configuracion.Seccion", null)
                        .WithMany()
                        .HasForeignKey("SeccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmsBackend.Domain.Configuracion.TipoMovimientoSeccion", b =>
                {
                    b.HasOne("SmsBackend.Domain.Configuracion.Seccion", null)
                        .WithMany()
                        .HasForeignKey("SeccionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmsBackend.Domain.TiposMovimiento.TipoMovimiento", null)
                        .WithMany()
                        .HasForeignKey("TipoMovimientoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmsBackend.Domain.Maestros.Maestro", b =>
                {
                    b.HasOne("SmsBackend.Domain.Maestros.Maestro", null)
                        .WithMany()
                        .HasForeignKey("FusionadoConId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
